import fs from 'fs';

const targetFile = 'D:/mydokumen/myproject/Apk_SiBangku/Apk_SiBangku/src/SiBangku.Web/Services/LanguageService.cs';

const baseKeysId = {
    // Navbar & Common
    "Nav_Home": "Beranda",
    "Nav_Booking": "Reservasi Meja",
    "Nav_BookNow": "Pesan Meja",
    "Nav_RestoAdmin": "Portal Mitra Resto",
    "Nav_ControlPlane": "Platform Control",
    "Nav_Language": "Bahasa",
    "Nav_Floorplan": "Denah Meja",
    "Nav_Features": "Keunggulan",
    "Nav_HowItWorks": "3 Langkah",
    "Nav_Tech": "Arsitektur",
    "Footer_Description": "Platform reservasi meja restoran multi-tenant modern dengan visualisasi denah meja akurat, pencegahan bentrok waktu, dan operasional kuliner efisien.",
    "Common_OpenNow": "Buka Sekarang",
    "Common_Close": "Tutup",
    "Common_Cancel": "Batal",
    "Common_Save": "Simpan",
    "Common_Confirm": "Konfirmasi",
    "Common_Loading": "Memuat...",

    // Hero Section
    "Hero_Eyebrow": "Sistem Reservasi Meja & Manajemen Restoran Berkelas",
    "Hero_Title_1": "Reservasi Meja Restoran",
    "Hero_Title_2": "Modern, Cepat & Tanpa Antre",
    "Hero_Subtitle": "Tingkatkan okupansi meja hingga 40% dan eliminasi no-show. Berikan pengalaman bersantap istimewa bagi pelanggan dengan pemindaian QR interaktif dan denah meja real-time.",
    "Hero_Btn_Book": "Reservasi Meja Sekarang",
    "Hero_Btn_ScanQR": "Buka Kamera / Scan QR",
    "Hero_Btn_RestoPortal": "Portal Pemilik Resto",
    "Hero_Search_Placeholder": "MASUKKAN KODE OUTLET RESTORAN ATAU SCAN QR",
    "Hero_Search_Btn": "Buka Portal",
    "Hero_Live_Status": "Sistem Live & Aktif",
    "Hero_Stat_Speed": "Konfirmasi Cepat",
    "Hero_Stat_Speed_Sub": "Slot diverifikasi dalam hitungan milidetik",
    "Hero_Stat_Capacity": "Anti Double-Booking",
    "Hero_Stat_Capacity_Sub": "Alokasi meja presisi dan bebas konflik",
    "Hero_Stat_Uptime": "99.9% Keandalan",
    "Hero_Stat_Uptime_Sub": "Kesiapan operasional di jam tersibuk",
    "Demo_Try": "Coba Demo:",
    "Demo_Directory": "Direktori",

    // Product Highlights / Pillars
    "Product_Badge": "MENGENAL SIBANGKU",
    "Product_Title": "Platform All-in-One untuk Tamu & Pengelola Restoran",
    "Product_Subtitle": "SiBangku dirancang untuk mengatasi masalah antrean panjang, ketidakpastian meja, dan kehilangan omzet akibat reservasi yang terbengkalai.",
    "Product_Card_1_Tag": "PENGALAMAN TAMU",
    "Product_Card_1_Title": "Pesan Meja Mandiri Tanpa Ribet",
    "Product_Card_1_Desc": "Pelanggan dapat memindai QR code standee akrilik di restoran dari HP maupun laptop, memilih waktu dan jumlah tamu, lalu menerima tiket digital resmi instan.",
    "Product_Card_2_Tag": "MANAJEMEN RESTO",
    "Product_Card_2_Title": "Denah Meja & Kapasitas Real-Time",
    "Product_Card_2_Desc": "Visualisasi denah meja akurat dengan koordinat ruang. Staf dan manajer outlet dapat memantau meja mana yang terisi, kosong, atau dalam antrean kedatangan.",
    "Product_Card_3_Tag": "OPTIMASI OMZET",
    "Product_Card_3_Title": "Sistem Auto-Release 15 Menit",
    "Product_Card_3_Desc": "Pemberi giliran meja otomatis yang melepaskan slot meja jika tamu tidak hadir dalam 15 menit, memastikan meja berputar optimal dan omzet restoran maksimal.",

    // Tech Grid
    "Tech_Badge": "TEKNOLOGI & ARSITEKTUR TANGGUH",
    "Tech_Title": "Fondasi Digital Berkecepatan Tinggi & Skalabel",
    "Tech_Subtitle": "Menggabungkan teknologi enterprise terkini untuk menjamin performa tanpa kompromi bagi ekosistem kuliner modern.",
    "Tech_1_Title": "Runtime C# .NET 9 Core",
    "Tech_1_Desc": "Pemrosesan transaksi super cepat dengan latensi rendah dan komputasi asinkronus berkapasitas tinggi.",
    "Tech_2_Title": "Isolasi Data Fisik Multi-Tenant",
    "Tech_2_Desc": "Setiap mitra restoran memiliki basis data terdedikasi demi integritas data dan kepatuhan privasi pelanggan.",
    "Tech_3_Title": "Pemindai Kamera Lintas Perangkat",
    "Tech_3_Desc": "Deteksi QR presisi tinggi yang kompatibel dengan kamera ponsel (depan/belakang) serta webcam laptop.",
    "Tech_4_Title": "Mesin Slot Bebas-Konflik",
    "Tech_4_Desc": "Algoritma verifikasi waktu matematis yang mencegah terjadinya tabrakan jam antar tamu di meja yang sama.",
    "Tech_5_Title": "Desain Sistem Adaptif White-Label",
    "Tech_5_Desc": "Tampilan antarmuka dinamis yang otomatis mengadopsi identitas logo, warna, dan tema khas setiap restoran.",
    "Tech_6_Title": "Kit Standee QR Siap Cetak",
    "Tech_6_Desc": "Generator poster QR beresolusi tajam siap cetak ukuran A4/A5 untuk dipasang langsung di meja atau pintu masuk.",

    // How It Works
    "How_Badge": "CARA KERJA",
    "How_Title": "3 Langkah Mudah Menikmati Meja Favorit",
    "How_Subtitle": "Proses mandiri yang cepat, jelas, dan tanpa menunggu antrean fisik.",
    "Step_1_Num": "01",
    "Step_1_Title": "Scan QR atau Masukkan Kode Resto",
    "Step_1_Desc": "Arahkan kamera HP/laptop ke poster standee di restoran atau ketik kode restoran mitra.",
    "Step_2_Num": "02",
    "Step_2_Title": "Tentukan Tanggal & Slot Jam",
    "Step_2_Desc": "Pilih tanggal kedatangan, estimasi jumlah tamu, dan jam santap yang masih tersedia.",
    "Step_3_Num": "03",
    "Step_3_Title": "Terima Tiket Digital Resmi",
    "Step_3_Desc": "Simpan kode booking unik dan tunjukkan kepada staf restoran saat Anda tiba.",

    // Interactive Preview Mockup & Floorplan Simulation
    "Mockup_Badge": "SIMULASI DENAH RESTORAN",
    "Mockup_Title": "Eksplorasi Denah & Alur Pemilihan Meja",
    "Mockup_Subtitle": "Klik meja di bawah ini untuk melihat zonasi ruang, estimasi suasana, dan alur pemesanan langsung.",
    "Mockup_Main_Plan": "Denah Meja Utama — Grand Bistro",
    "Mockup_Capacity_Subtitle": "Kapasitas: 24 Kursi • 3 Zona Bersantap",
    "Mockup_Status_Available": "Tersedia",
    "Mockup_Status_Hold": "Hold",
    "Mockup_Status_Booked": "Terisi",
    "Mockup_Status_Selected": "Dipilih",
    "Mockup_Zone_VIP": "ZONA VIP SUITE",
    "Mockup_Zone_Main": "MAIN DINING HALL",
    "Mockup_Zone_Skyline": "SKYLINE TERRACE",
    "Mockup_Tag_Private": "Privat",
    "Mockup_Tag_Lobby": "Lobby",
    "Mockup_Tag_Outdoor": "Outdoor",
    "Mockup_Table": "Meja",
    "Mockup_Seats": "Kursi",
    "Mockup_Table_Ready": "Siap",
    "Mockup_Table_Occupied": "Terisi",
    "Mockup_Table_Hold_15m": "Hold 15m",
    "Mockup_Table_1_Desc": "Sofa Booth Mewah • 6 Kursi",
    "Mockup_Table_2_Desc": "Intimate Candlelight • 2 Kursi",
    "Mockup_Table_3_Desc": "Family Table • 4 Kursi",
    "Mockup_Table_4_Desc": "Center Dining • 6 Kursi",
    "Mockup_Table_5_Desc": "Glass Window Side • 2 Kursi",
    "Mockup_Table_6_Desc": "Outdoor Balcony • 4 Kursi",
    "Mockup_Selected_Table": "MEJA TERPILIH",
    "Mockup_Capacity_Spend": "KAPASITAS & MIN. SPEND",
    "Mockup_Ambiance_Feature": "SUASANA & FITUR",
    "Mockup_Book_Action": "Pesan",
    "Zone_Vip_Name": "VIP Suite",
    "Zone_Main_Name": "Main Hall",
    "Zone_Skyline_Name": "Skyline Terrace",
    "Ambiance_1": "Privat, Sofa Mewah, Lampu Gantung Warm Amber",
    "Ambiance_2": "Intimate Candlelight, Meja Berdua Romantis",
    "Ambiance_3": "Meja Bundar Tengah, Nuansa Santai",
    "Ambiance_4": "Meja Keluarga Nyaman, Dekat Lorong Utama",
    "Ambiance_5": "Pemandangan Jendela Luar, Angin Semilir",
    "Ambiance_6": "Balkon Terbuka, Pemandangan Lampu Kota",
    "Ambiance_Default": "Suasana Santap Eksklusif",
    "MinSpend_Free": "Bebas Min. Order",

    // Key Features & Advantages
    "Features_Badge": "KEUNGGULAN UTAMA",
    "Features_Title": "Dirancang Presisi untuk Industri Kuliner",
    "Features_Subtitle": "Fondasi matematis mutakhir yang mengeliminasi kerugian restoran dan memberikan kepastian tempat bagi tamu.",
    "Features_Self_Booking": "Reservasi Mandiri",
    "Features_Self_Booking_Sub": "Tamu memesan kapan saja tanpa harus menunggu staf.",

    // Testimonial
    "Testimonial_Quote": "\"Dengan SiBangku, perputaran meja kami meningkat lebih dari 35% dan masalah no-show dapat dieliminasi secara otomatis tanpa perlu pencatatan manual di buku reservasi kasir.\"",
    "Testimonial_Author": "Marco Santoso",
    "Testimonial_Role": "Director of F&B Operations • Grand Bistro Dining & Lounge",

    // Quick Rail & System
    "Quick_Home": "Beranda",
    "Quick_Floorplan": "Denah Meja",
    "Quick_Features": "Keunggulan",
    "Quick_How": "Cara Kerja",
    "Quick_Tech": "Arsitektur",
    "Quick_CTA": "Mulai Reservasi",
    "System_Operational": "Semua sistem beroperasi normal",
    "System_Portals": "Portals:",

    // CTA Section
    "CTA_Title": "Mulai Transformasi Reservasi Restoran Anda Hari Ini",
    "CTA_Subtitle": "Bergabunglah dengan ratusan meja restoran yang telah terkelola secara efisien, bebas bentrok, dan menguntungkan.",
    "CTA_Btn_Explore": "Pesan Meja Tamu",
    "CTA_Btn_Partner": "Masuk Sebagai Mitra Restoran",

    // Booking Portal
    "Booking_Title_Default": "Portal Reservasi Meja Mandiri",
    "Booking_Subtitle_Default": "Masukkan kode outlet restoran atau scan QR code standee di meja untuk melihat ketersediaan real-time",
    "Booking_Search_Placeholder": "KODE RESTORAN",
    "Booking_Search_Btn": "Cari Resto",
    "Booking_Scan_Btn": "Scan QR Meja",
    "Booking_Active_Outlet": "Outlet Aktif",
    "Booking_Hours": "Jam Buka",
    "Booking_Slot_Duration": "Durasi Slot",
    "Booking_Minutes": "Menit",
    "Booking_Select_Outlet_Prompt": "Tentukan Outlet Restoran Mitra",
    "Booking_Select_Outlet_Hint": "Silakan masukkan kode restoran pada kolom di atas atau scan QR Code standee yang tersedia di meja restoran.",
    "Booking_Connecting": "Menghubungkan ke Basis Data Restoran...",
    "Booking_Step1_Title": "Tentukan Tanggal & Tamu",
    "Booking_Date_Label": "Tanggal Kunjungan",
    "Booking_Guests_Label": "Jumlah Tamu",
    "Booking_Guests_Suffix": "Orang",
    "Booking_Slots_Title": "Slot Waktu Tersedia:",
    "Booking_Slot_Full": "Penuh",
    "Booking_Slot_Tables_Count": "Meja",
    "Booking_No_Slots": "Tidak ada slot waktu tersedia pada tanggal ini.",
    "Booking_Step2_Title": "Informasi Kontak Pemesan",
    "Booking_Prompt_Select_Slot": "Silakan pilih salah satu slot waktu yang tersedia pada panel di sebelah kiri.",
    "Booking_Selected_Slot_Label": "SLOT TERPILIH:",
    "Booking_Name_Label": "Nama Lengkap Pemesan",
    "Booking_Name_Placeholder": "Nama Lengkap Anda",
    "Booking_Email_Label": "Alamat Email",
    "Booking_Email_Placeholder": "alamat@email.com",
    "Booking_Phone_Label": "No. WhatsApp / Telepon",
    "Booking_Phone_Placeholder": "08xxxxxxxxxx",
    "Booking_Notes_Label": "Catatan Khusus (Opsional)",
    "Booking_Notes_Placeholder": "Permintaan khusus: area dekat jendela, kursi bayi, acara keluarga, dll.",
    "Booking_Submit_Btn": "Konfirmasi & Buat Reservasi",
    "Booking_Submitting": "Memproses Reservasi Anda...",
    "Booking_Security_Note": "Terenkripsi & terhubung langsung dengan sistem reservasi outlet.",

    // Ticket Confirmation
    "Ticket_Success_Title": "Reservasi Berhasil Dikonfirmasi!",
    "Ticket_Success_Desc": "Kode booking resmi Anda adalah {0}. Simpan tiket digital ini saat kedatangan.",
    "Ticket_Header_Title": "Tiket Reservasi Meja Digital",
    "Ticket_Header_Subtitle": "Tunjukkan tiket ini kepada staf resepsionis restoran.",
    "Ticket_Booking_Code": "KODE BOOKING",
    "Ticket_Status_Registered": "Terdaftar",
    "Ticket_Restaurant": "Restoran Tujuan",
    "Ticket_Guest_Name": "Nama Pemesan",
    "Ticket_Date_Time": "Tanggal & Waktu",
    "Ticket_Guests": "Jumlah Tamu",
    "Ticket_Notes": "Catatan Khusus:",
    "Ticket_Btn_Print": "Cetak Tiket",
    "Ticket_Btn_New": "Reservasi Baru",
    "Ticket_Btn_Back": "Kembali ke Form",

    // Scanner Modal
    "Scanner_Modal_Title": "Pemindai Kamera QR Restoran",
    "Scanner_Modal_Subtitle": "Arahkan kamera ke QR Code standee meja atau banner restoran. Mendukung kamera HP & laptop.",
    "Scanner_Camera_Label": "Pilih Perangkat Kamera:",
    "Scanner_Scanning_Status": "Mencari QR Code... Pastikan pencahayaan cukup.",
    "Scanner_Torch_Toggle": "Lampu Flash",
    "Scanner_Flip_Camera": "Ganti Kamera",
    "Scanner_Upload_Hint": "Atau upload foto / screenshot QR code:",
    "Scanner_Upload_Btn": "Pilih File Gambar",
    "Scanner_Close_Btn": "Tutup Pemindai",
    "Scanner_Success": "QR Berhasil Dideteksi! Mengalihkan ke outlet...",
    "Scanner_Permission_Denied": "Izin kamera ditolak atau perangkat kamera tidak ditemukan. Silakan izinkan akses kamera di browser Anda atau gunakan upload gambar.",

    // Language Selector
    "Lang_Modal_Title": "Pilih Bahasa",
    "Lang_Modal_Subtitle": "Pilih bahasa tampilan yang Anda inginkan",
    "Lang_Search_Placeholder": "Cari bahasa... (mis. Japanese, العربية, Français)",
    "Lang_Available": "bahasa tersedia",
    "Lang_Showing": "Menampilkan",
    "Lang_Results": "hasil",
    "Lang_No_Results": "Tidak ada bahasa yang cocok dengan pencarian Anda.",
    "Lang_Current": "Aktif (Sedang Digunakan)",
    "Lang_Supported_Pill": "Didukung Penuh",
    "Lang_Quick_Title": "Bahasa Populer & Cepat Digunakan:"
};

const baseKeysEn = {
    // Navbar & Common
    "Nav_Home": "Home",
    "Nav_Booking": "Table Booking",
    "Nav_BookNow": "Book a Table",
    "Nav_RestoAdmin": "Resto Admin Portal",
    "Nav_ControlPlane": "Platform Control",
    "Nav_Language": "Language",
    "Nav_Floorplan": "Floorplan",
    "Nav_Features": "Features",
    "Nav_HowItWorks": "3 Steps",
    "Nav_Tech": "Architecture",
    "Footer_Description": "Enterprise multi-tenant table reservation, interactive floorplan visualization, and high-density restaurant operations platform.",
    "Common_OpenNow": "Open Now",
    "Common_Close": "Close",
    "Common_Cancel": "Cancel",
    "Common_Save": "Save",
    "Common_Confirm": "Confirm",
    "Common_Loading": "Loading...",

    // Hero Section
    "Hero_Eyebrow": "Fine Dining Reservation & Table Management",
    "Hero_Title_1": "Intelligent Table Booking",
    "Hero_Title_2": "Modern, Fast & Seamless",
    "Hero_Subtitle": "Elevate restaurant table turn rates up to 40% and eliminate no-shows. Deliver a distinctive dining journey through interactive QR scanning and real-time floor plans.",
    "Hero_Btn_Book": "Reserve a Table Now",
    "Hero_Btn_ScanQR": "Open Camera / Scan QR",
    "Hero_Btn_RestoPortal": "Restaurant Owner Portal",
    "Hero_Search_Placeholder": "ENTER RESTAURANT OUTLET CODE OR SCAN QR",
    "Hero_Search_Btn": "Access Portal",
    "Hero_Live_Status": "Platform Live & Active",
    "Hero_Stat_Speed": "Rapid Confirmation",
    "Hero_Stat_Speed_Sub": "Sub-second millisecond slot verification",
    "Hero_Stat_Capacity": "Anti Double-Booking",
    "Hero_Stat_Capacity_Sub": "Conflict-free mathematical slot engine",
    "Hero_Stat_Uptime": "99.9% System Uptime",
    "Hero_Stat_Uptime_Sub": "Operational resilience during peak dining",
    "Demo_Try": "Try Demo:",
    "Demo_Directory": "Directory",

    // Product Highlights / Pillars
    "Product_Badge": "ABOUT SIBANGKU",
    "Product_Title": "All-in-One Culinary Operating Engine for Diners & Operators",
    "Product_Subtitle": "Engineered from the ground up to eradicate long waiting lines, table uncertainty, and revenue forfeiture from unmanaged reservations.",
    "Product_Card_1_Tag": "GUEST JOURNEY",
    "Product_Card_1_Title": "Frictionless Self-Reservation",
    "Product_Card_1_Desc": "Guests simply scan the restaurant's acrylic QR standee from any phone or laptop, pick desired party size, and instantly obtain a verified digital ticket.",
    "Product_Card_2_Tag": "OPERATIONS",
    "Product_Card_2_Title": "Real-Time Spatial Floorplans",
    "Product_Card_2_Desc": "Precise spatial floor plan visualization. Outlet staff and hosts monitor occupied, vacant, and imminent arrival tables in real-time.",
    "Product_Card_3_Tag": "REVENUE ENGINE",
    "Product_Card_3_Title": "15-Minute Auto-Release Daemon",
    "Product_Card_3_Desc": "Intelligent table rotation daemon automatically frees unseated reservations after 15 minutes of grace time, maximizing daily revenue.",

    // Tech Grid
    "Tech_Badge": "ENTERPRISE ARCHITECTURE",
    "Tech_Title": "Built on a High-Speed, Scalable Digital Foundation",
    "Tech_Subtitle": "Blending modern enterprise technologies to guarantee uncompromised performance under high-density dining workloads.",
    "Tech_1_Title": "Blazing C# .NET 9 Core",
    "Tech_1_Desc": "Sub-millisecond reservation transactions with high-throughput asynchronous computing during peak volume.",
    "Tech_2_Title": "Multi-Tenant Physical DB Isolation",
    "Tech_2_Desc": "Every restaurant partner enjoys an isolated physical database partition ensuring absolute customer data privacy.",
    "Tech_3_Title": "Cross-Device Universal QR Engine",
    "Tech_3_Desc": "High-accuracy optical camera recognition supporting mobile front/back sensors and laptop webcams flawlessly.",
    "Tech_4_Title": "Conflict-Free Slot Allocation",
    "Tech_4_Desc": "Rigorous algebraic scheduling engine eliminating table collision risks across identical seating windows.",
    "Tech_5_Title": "Adaptive White-Label System",
    "Tech_5_Desc": "Dynamic UI automatically tailoring branding, color accents, and typography to mirror each restaurant's brand.",
    "Tech_6_Title": "Ready-to-Print QR Standee Kit",
    "Tech_6_Desc": "Vector-sharp PDF export generating high-resolution A4/A5 acrylic standee artwork ready for table display.",

    // How It Works
    "How_Badge": "HOW IT WORKS",
    "How_Title": "3 Effortless Steps to Your Perfect Table",
    "How_Subtitle": "A swift, transparent self-service journey without physical waiting queues.",
    "Step_1_Num": "01",
    "Step_1_Title": "Scan QR or Enter Outlet Code",
    "Step_1_Desc": "Point your phone camera at the dining table standee or type the restaurant code.",
    "Step_2_Num": "02",
    "Step_2_Title": "Choose Date & Time Slot",
    "Step_2_Desc": "Select your visit date, number of dining companions, and available dining hour.",
    "Step_3_Num": "03",
    "Step_3_Title": "Receive Official Digital Ticket",
    "Step_3_Desc": "Save your unique booking code and present it to the restaurant host upon arrival.",

    // Interactive Preview Mockup & Floorplan Simulation
    "Mockup_Badge": "RESTAURANT FLOOR PLAN SIMULATION",
    "Mockup_Title": "Explore Floor Plan & Table Selection Flow",
    "Mockup_Subtitle": "Click a table below to preview room zoning, ambiance, and direct booking flow.",
    "Mockup_Main_Plan": "Main Dining Floor Plan — Grand Bistro",
    "Mockup_Capacity_Subtitle": "Capacity: 24 Seats • 3 Dining Zones",
    "Mockup_Status_Available": "Available",
    "Mockup_Status_Hold": "Hold",
    "Mockup_Status_Booked": "Occupied",
    "Mockup_Status_Selected": "Selected",
    "Mockup_Zone_VIP": "VIP SUITE ZONE",
    "Mockup_Zone_Main": "MAIN DINING HALL",
    "Mockup_Zone_Skyline": "SKYLINE TERRACE",
    "Mockup_Tag_Private": "Private",
    "Mockup_Tag_Lobby": "Lobby",
    "Mockup_Tag_Outdoor": "Outdoor",
    "Mockup_Table": "Table",
    "Mockup_Seats": "Seats",
    "Mockup_Table_Ready": "Ready",
    "Mockup_Table_Occupied": "Occupied",
    "Mockup_Table_Hold_15m": "Hold 15m",
    "Mockup_Table_1_Desc": "Luxury Sofa Booth • 6 Seats",
    "Mockup_Table_2_Desc": "Intimate Candlelight • 2 Seats",
    "Mockup_Table_3_Desc": "Family Table • 4 Seats",
    "Mockup_Table_4_Desc": "Center Dining • 6 Seats",
    "Mockup_Table_5_Desc": "Glass Window Side • 2 Seats",
    "Mockup_Table_6_Desc": "Outdoor Balcony • 4 Seats",
    "Mockup_Selected_Table": "SELECTED TABLE",
    "Mockup_Capacity_Spend": "CAPACITY & MIN. SPEND",
    "Mockup_Ambiance_Feature": "AMBIANCE & FEATURES",
    "Mockup_Book_Action": "Book",
    "Zone_Vip_Name": "VIP Suite",
    "Zone_Main_Name": "Main Hall",
    "Zone_Skyline_Name": "Skyline Terrace",
    "Ambiance_1": "Private, Luxury Sofa, Warm Amber Chandelier",
    "Ambiance_2": "Intimate Candlelight, Romantic Table for Two",
    "Ambiance_3": "Center Round Table, Relaxed Atmosphere",
    "Ambiance_4": "Comfortable Family Table, Near Main Hallway",
    "Ambiance_5": "Outer Window View, Gentle Breeze",
    "Ambiance_6": "Open-Air Balcony, City Lights Panorama",
    "Ambiance_Default": "Exclusive Dining Atmosphere",
    "MinSpend_Free": "No Min. Spend",

    // Key Features & Advantages
    "Features_Badge": "KEY ADVANTAGES",
    "Features_Title": "Precision Engineered for the Culinary Industry",
    "Features_Subtitle": "Cutting-edge mathematical foundation that eliminates restaurant losses and provides guaranteed seating for guests.",
    "Features_Self_Booking": "Self-Service Booking",
    "Features_Self_Booking_Sub": "Guests reserve anytime without waiting for staff.",

    // Testimonial
    "Testimonial_Quote": "\"With SiBangku, our table turnover increased by over 35% and no-shows were eliminated automatically without manual cashier reservation logs.\"",
    "Testimonial_Author": "Marco Santoso",
    "Testimonial_Role": "Director of F&B Operations • Grand Bistro Dining & Lounge",

    // Quick Rail & System
    "Quick_Home": "Home",
    "Quick_Floorplan": "Floor Plan",
    "Quick_Features": "Features",
    "Quick_How": "How It Works",
    "Quick_Tech": "Architecture",
    "Quick_CTA": "Book Now",
    "System_Operational": "All systems operational",
    "System_Portals": "Portals:",

    // CTA Section
    "CTA_Title": "Transform Your Restaurant Reservations Today",
    "CTA_Subtitle": "Join hundreds of dining tables operating with conflict-free certainty and heightened profitability.",
    "CTA_Btn_Explore": "Book a Guest Table",
    "CTA_Btn_Partner": "Partner With SiBangku",

    // Booking Portal
    "Booking_Title_Default": "Guest Table Reservation Portal",
    "Booking_Subtitle_Default": "Enter restaurant code or scan table standee QR code to inspect live table availability",
    "Booking_Search_Placeholder": "RESTAURANT CODE",
    "Booking_Search_Btn": "Find Restaurant",
    "Booking_Scan_Btn": "Scan Table QR",
    "Booking_Active_Outlet": "Active Outlet",
    "Booking_Hours": "Opening Hours",
    "Booking_Slot_Duration": "Slot Duration",
    "Booking_Minutes": "Minutes",
    "Booking_Select_Outlet_Prompt": "Select a Partner Restaurant Outlet",
    "Booking_Select_Outlet_Hint": "Please enter an outlet code above or scan the table standee QR code present at the restaurant.",
    "Booking_Connecting": "Connecting to Restaurant Database...",
    "Booking_Step1_Title": "Select Date & Party Size",
    "Booking_Date_Label": "Reservation Date",
    "Booking_Guests_Label": "Guest Count",
    "Booking_Guests_Suffix": "Guests",
    "Booking_Slots_Title": "Available Time Slots:",
    "Booking_Slot_Full": "Fully Booked",
    "Booking_Slot_Tables_Count": "Tables Available",
    "Booking_No_Slots": "No available time slots found for the chosen date.",
    "Booking_Step2_Title": "Contact Information",
    "Booking_Prompt_Select_Slot": "Please select one of the available time slots on the left panel to proceed.",
    "Booking_Selected_Slot_Label": "SELECTED SLOT:",
    "Booking_Name_Label": "Primary Guest Name",
    "Booking_Name_Placeholder": "Your Full Legal Name",
    "Booking_Email_Label": "Email Address",
    "Booking_Email_Placeholder": "you@domain.com",
    "Booking_Phone_Label": "WhatsApp / Phone Number",
    "Booking_Phone_Placeholder": "+62 812-xxxx-xxxx",
    "Booking_Notes_Label": "Special Requests (Optional)",
    "Booking_Notes_Placeholder": "E.g., Window seating, high chair needed, anniversary celebration, etc.",
    "Booking_Submit_Btn": "Confirm & Create Reservation",
    "Booking_Submitting": "Securing Your Reservation...",
    "Booking_Security_Note": "Encrypted & synchronized directly with the outlet's operational ledger.",

    // Ticket Confirmation
    "Ticket_Success_Title": "Reservation Successfully Confirmed!",
    "Ticket_Success_Desc": "Your official reservation code is {0}. Please keep this digital receipt for your arrival.",
    "Ticket_Header_Title": "Digital Table Reservation Ticket",
    "Ticket_Header_Subtitle": "Present this digital ticket to the host upon arrival.",
    "Ticket_Booking_Code": "BOOKING CODE",
    "Ticket_Status_Registered": "Confirmed",
    "Ticket_Restaurant": "Restaurant",
    "Ticket_Guest_Name": "Guest Name",
    "Ticket_Date_Time": "Date & Time",
    "Ticket_Guests": "Party Size",
    "Ticket_Notes": "Special Notes:",
    "Ticket_Btn_Print": "Print Pass",
    "Ticket_Btn_New": "New Reservation",
    "Ticket_Btn_Back": "Back to Form",

    // Scanner Modal
    "Scanner_Modal_Title": "Restaurant QR Camera Scanner",
    "Scanner_Modal_Subtitle": "Align your device camera with the table standee QR code or print banner. Supports mobile and laptop cameras.",
    "Scanner_Camera_Label": "Active Optical Sensor:",
    "Scanner_Scanning_Status": "Searching for valid QR code... Ensure balanced illumination.",
    "Scanner_Torch_Toggle": "Torchlight",
    "Scanner_Flip_Camera": "Flip Camera",
    "Scanner_Upload_Hint": "Or upload a saved QR screenshot / photo:",
    "Scanner_Upload_Btn": "Choose Image File",
    "Scanner_Close_Btn": "Dismiss Scanner",
    "Scanner_Success": "QR Code Recognized! Navigating to restaurant...",
    "Scanner_Permission_Denied": "Camera permission was denied or no video input sensor was discovered. Please grant camera permission in your browser or upload an image.",

    // Language Selector
    "Lang_Modal_Title": "Select Language",
    "Lang_Modal_Subtitle": "Choose your preferred display language for the platform",
    "Lang_Search_Placeholder": "Search language... (e.g. Indonesian, Japanese, French)",
    "Lang_Available": "languages available",
    "Lang_Showing": "Showing",
    "Lang_Results": "results",
    "Lang_No_Results": "No languages match your search.",
    "Lang_Current": "Active (Current)",
    "Lang_Supported_Pill": "Fully Supported",
    "Lang_Quick_Title": "Popular & Instant Languages:"
};

fs.writeFileSync('D:/mydokumen/myproject/Apk_SiBangku/Apk_SiBangku/.scratch/dict_id_en.json', JSON.stringify({ id: baseKeysId, en: baseKeysEn }, null, 2), 'utf8');
console.log("Wrote base dictionary JSON.");
